config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts do
    resources :comments
  end
  get '/categories/:category_id', to: 'posts#index', as: 'categories_index'
  get '/search', to: 'posts#index'  
  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments
    
    def self.search(args)
      if args[:category_id] 
        out = Post.where(["category_id = ?", args[:category_id]])
      elsif args[:tag_id]
        out = Post.joins(:post_tags).where(["post_tags.tag_id = ?", args[:tag_id]])      
      elsif args[:slug]
        out = Post.where(["user_id = ?", args[:slug].to_i])
      elsif args[:string]
        out = Post.joins(:user).where(["description LIKE ? 
                                        OR users.firstname LIKE ?
                                        OR users.lastname  LIKE ?",
                                        "%#{args[:string]}%",
                                        "%#{args[:string]}%",
                                        "%#{args[:string]}%"])
      else
        out = Post.all
      end
      if args[:offset]
        out.limit(5).offset(args[:offset])
      else
        out.limit(5)
      end
    end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    def new
      @comment = Comment.new
    end
    def create
      @comment = @posts.comments.create(comment_params)
      if @comment.save
        redirect_to @posts
      else
        flash.now[:danger] = "error"
      end
    end

private
    def comment_params
        params.require(:comment)
              .permit(
                  :mail,
                  :content
              )
    end

    def find_post
      @posts = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
respond_to :js, :json, :html
before_action :authenticate_user!, except: [:index,:show]
    def index
        @posts = Post.search(params)
    end

    def new
        @posts = Post.new
    end
    def show
        @posts = Post.find(params[:id])
    end
    def create
        @posts = Post.new(posts_params)
        if @posts.save
            redirect_to posts_path
        else
            render template '/posts/new'
        end
    end
private
    def posts_params
        params.require(:post)
              .permit(
                  :title,
                  :content,
                  :category_id
              ).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.haml
= form_for [@posts,@posts.comments.build] do |f|
  .form-group
    =f.label :mail, class:'form-label required'
    =f.text_field :mail, class:'form-control'
  .form-group
    =f.label :content, class:'form-label required'
    =f.text_area :content, class:'form-control'
  .form-group
    =f.submit "Poster", class: 'btn-btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Dosis", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    .header
      = render partial: '/shared/header'
    .container.content
      = yield

app/views/posts/index.html.haml
- @posts.each do |post|
  .card.posts
    .card-block
      %h4.card-title
        %a{href: post_path(post)}=post.title
      %p.card-text=post.content
      %span.badge.badge-default= post.category.name
      %div= post.created_at

app/views/posts/new.html.haml
%h2= "Nouveau post"
- if @posts.errors.any?
  .row
    .col-xs-8.col-xs-offset-2.errors
      %h2
        = pluralize(@posts.errors.count, "error")
        = t('errors', count: @listing.errors.count)
      %ul
        - @posts.errors.full_messages.each do |msg|
          %li= msg

= form_for @posts, class: 'form', html: {multipart: true} do |f|
  .form-group
    = f.label :category_id, class: 'form-label required'
    = f.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'}
  .form-group
    =f.label :content, class:'form-label required'
    =f.text_area :content, class:'form-control'
  .form-group
    =f.label :title, class:'form-label required'
    =f.text_field :title, class:'form-control'
  .form-group
    =f.submit "Poster", class: 'btn-btn-primary'

app/views/posts/show.html.haml
.row
%h4.title
  %p= "Titre: "+@posts.title
%div
  %p= "Contenu: "
  %br/
  %p= @posts.content
%div
  %span.badge.badge-default=@posts.category.name
  - @posts.comments.each do |comment|
    .panel.panel-default
      .panel-heading
        = comment.mail+" dis :"
      .panel-body 
        = comment.content
%p= link_to "Add Comment", new_post_comment_path(post_id: @posts.id)

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.bg-inverse
  .row
    %a.navbar-brand{href: root_path}
      ="Blog"
    - if current_user
      %a{href: destroy_user_session_path, class:'center-text pull-right col-1', 'data-method' => 'delete'}
        ="Log out"
    - else 
      %a{href: new_user_session_path, class:'center-text pull-right col-1'}
        ="Log in"